<?php

namespace App\Http\Controllers;

use App\Models\AdminAuditLog;
use App\Models\User;
use App\Support\Tenancy;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ImpersonationController extends Controller
{
    /**
     * Entered on the TARGET TENANT'S OWN domain via a short-lived signed link
     * generated by Platform\Tenants\Show::impersonate(). Session cookies here
     * are host-only (SESSION_DOMAIN=null), so this is the only place the
     * session/audit log for an impersonation can actually be established —
     * logging in on the central Platform domain would never carry over.
     */
    public function enter(Request $request, int $impersonator, int $user)
    {
        abort_unless($request->hasValidSignature(false), 403);
        abort_unless(Tenancy::check(), 404);

        $operator = User::findOrFail($impersonator);
        abort_unless($operator->tenant_id === null, 403);

        $owner = User::where('tenant_id', Tenancy::id())->findOrFail($user);

        $request->session()->put([
            'impersonator_id' => $operator->id,
            'impersonating_tenant_id' => Tenancy::id(),
        ]);

        AdminAuditLog::create([
            'user_id' => $operator->id,
            'tenant_id' => Tenancy::id(),
            'action' => 'impersonation_started',
            'meta' => ['target_user_id' => $owner->id],
        ]);

        Auth::login($owner);

        return redirect()->route('dashboard');
    }

    /**
     * Ends impersonation on the tenant's domain and sends the browser back to
     * the central Platform domain, where its own still-valid session cookie
     * (untouched throughout impersonation, since cookies are host-only)
     * naturally re-establishes the operator's identity.
     */
    public function stop(Request $request)
    {
        abort_unless($request->session()->has('impersonator_id'), 403);

        $impersonatorId = $request->session()->pull('impersonator_id');
        $tenantId = $request->session()->pull('impersonating_tenant_id');

        AdminAuditLog::create([
            'user_id' => $impersonatorId,
            'tenant_id' => $tenantId,
            'action' => 'impersonation_stopped',
        ]);

        Auth::logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();

        $central = config('tenancy.central_domains')[0] ?? $request->getHost();
        $port = $request->getPort();
        $portSuffix = in_array($port, [80, 443], true) ? '' : ':'.$port;

        return redirect()->to($request->getScheme().'://'.$central.$portSuffix.route('platform.dashboard', [], false));
    }
}
